let a = +prompt('Введите первое число')
let b = +prompt('Введите второе число')
c = a+b
d = a-b
e = a*b
f = a/b
g = a**b
alert(`${a}+${b}=${c}`)
alert(`${a}-${b}=${d}`)
alert(`${a}*${b}=${e}`)
alert(`${a}/${b}=${f}`)
alert(`${a}^${b}=${g}`)